/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as EntregadorRouteImport } from './routes/entregador'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolicitanteIndexRouteImport } from './routes/solicitante/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SolicitanteNovaRouteImport } from './routes/solicitante/nova'
import { Route as AdminEntregadoresRouteImport } from './routes/admin/entregadores'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadorRoute = EntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitanteIndexRoute = SolicitanteIndexRouteImport.update({
  id: '/solicitante/',
  path: '/solicitante/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SolicitanteNovaRoute = SolicitanteNovaRouteImport.update({
  id: '/solicitante/nova',
  path: '/solicitante/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntregadoresRoute = AdminEntregadoresRouteImport.update({
  id: '/entregadores',
  path: '/entregadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/entregador': typeof EntregadorRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/solicitante/nova': typeof SolicitanteNovaRoute
  '/admin/': typeof AdminIndexRoute
  '/solicitante/': typeof SolicitanteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entregador': typeof EntregadorRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/solicitante/nova': typeof SolicitanteNovaRoute
  '/admin': typeof AdminIndexRoute
  '/solicitante': typeof SolicitanteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/entregador': typeof EntregadorRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/solicitante/nova': typeof SolicitanteNovaRoute
  '/admin/': typeof AdminIndexRoute
  '/solicitante/': typeof SolicitanteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/entregador'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/entregadores'
    | '/solicitante/nova'
    | '/admin/'
    | '/solicitante/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entregador'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/entregadores'
    | '/solicitante/nova'
    | '/admin'
    | '/solicitante'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/entregador'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/entregadores'
    | '/solicitante/nova'
    | '/admin/'
    | '/solicitante/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EntregadorRoute: typeof EntregadorRoute
  SobreRoute: typeof SobreRoute
  SolicitanteNovaRoute: typeof SolicitanteNovaRoute
  SolicitanteIndexRoute: typeof SolicitanteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregador': {
      id: '/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof EntregadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitante/': {
      id: '/solicitante/'
      path: '/solicitante'
      fullPath: '/solicitante/'
      preLoaderRoute: typeof SolicitanteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/solicitante/nova': {
      id: '/solicitante/nova'
      path: '/solicitante/nova'
      fullPath: '/solicitante/nova'
      preLoaderRoute: typeof SolicitanteNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entregadores': {
      id: '/admin/entregadores'
      path: '/entregadores'
      fullPath: '/admin/entregadores'
      preLoaderRoute: typeof AdminEntregadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEntregadoresRoute: typeof AdminEntregadoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEntregadoresRoute: AdminEntregadoresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EntregadorRoute: EntregadorRoute,
  SobreRoute: SobreRoute,
  SolicitanteNovaRoute: SolicitanteNovaRoute,
  SolicitanteIndexRoute: SolicitanteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
